### ISSUE TITLE
cmake build error:  Unknown CMake command "protobuf_generate_cpp".

### ISSUE THREAD

**Issue by mjsduncan** [Habush/atomspace-rpc#2]
after installing gRPC from repo i get this error:

```
CMake Error at src/CMakeLists.txt:18 (protobuf_generate_cpp):
  Unknown CMake command "protobuf_generate_cpp".
```

**Comment by Habush** [comment]
I have updated the README to mention the `protobuf` dependency. You can install it using the following commands

```bash
git clone https://github.com/google/protobuf.git
cd protobuf
git submodule update --init --recursive
./autogen.sh
make
make install
sudo ldconfig

```

**Comment by mjsduncan** [comment]
this needs ./configure after ./autogen.sh
i have a protobuf packge libprotobuf17, is there a way to use that instead?

**Comment by mjsduncan** [comment]
i believe protobuf is already required for one of the opencog repo builds....

**Comment by mjsduncan** [comment]
if i add `set(protobuf_MODULE_COMPATIBLE ON CACHE BOOL "")` to the beginning of `CMakeLists.txt` then previously installed protobuf package is found and `cmake ..` is successful.

from [https://stackoverflow.com/questions/52533396/cmake-cant-find-protobuf-pr](https://stackoverflow.com/questions/52533396/cmake-cant-find-protobuf-pr)
